name: sunruleapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.4
  page_transition: ^2.0.9
  custom_radio_grouped_button: ^2.1.2+2
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.9
  razorpay_flutter: ^1.3.2
  firebase_core: ^1.23.0
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  firebase_auth: ^3.3.20
  flutter_range_slider: ^1.5.0
  multi_select_flutter: ^4.1.2






dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

